application: stalkerapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  secure: never

builtins:
- remote_api: on